# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\add_partner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_partner_def(object):
    def setupUi(self, Add_partner_def):
        Add_partner_def.setObjectName("Add_partner_def")
        Add_partner_def.resize(615, 565)
        Add_partner_def.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.verticalLayoutWidget = QtWidgets.QWidget(Add_partner_def)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 60, 347, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_partnertype = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_partnertype.setMaxLength(3)
        self.lineEdit_partnertype.setObjectName("lineEdit_partnertype")
        self.verticalLayout.addWidget(self.lineEdit_partnertype)
        self.label_part_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_part_name.setObjectName("label_part_name")
        self.verticalLayout.addWidget(self.label_part_name)
        self.lineEdit_partname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_partname.setObjectName("lineEdit_partname")
        self.verticalLayout.addWidget(self.lineEdit_partname)
        self.label_director = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_director.setObjectName("label_director")
        self.verticalLayout.addWidget(self.label_director)
        self.lineEdit_dname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_dname.setObjectName("lineEdit_dname")
        self.verticalLayout.addWidget(self.lineEdit_dname)
        self.label_email = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_email.setObjectName("label_email")
        self.verticalLayout.addWidget(self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout.addWidget(self.lineEdit_email)
        self.label_telephone = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_telephone.setObjectName("label_telephone")
        self.verticalLayout.addWidget(self.label_telephone)
        self.lineEdit_telep = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_telep.setText("")
        self.lineEdit_telep.setMaxLength(10)
        self.lineEdit_telep.setObjectName("lineEdit_telep")
        self.verticalLayout.addWidget(self.lineEdit_telep)
        self.label_ur_addres = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_ur_addres.setObjectName("label_ur_addres")
        self.verticalLayout.addWidget(self.label_ur_addres)
        self.lineEdit_uradd = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_uradd.setObjectName("lineEdit_uradd")
        self.verticalLayout.addWidget(self.lineEdit_uradd)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lineEdit_inn = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_inn.setMaxLength(12)
        self.lineEdit_inn.setObjectName("lineEdit_inn")
        self.verticalLayout.addWidget(self.lineEdit_inn)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.lineEdit_rating = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_rating.setMaxLength(3)
        self.lineEdit_rating.setObjectName("lineEdit_rating")
        self.verticalLayout.addWidget(self.lineEdit_rating)
        self.pushButton_add_partner = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(115)
        sizePolicy.setVerticalStretch(77)
        sizePolicy.setHeightForWidth(self.pushButton_add_partner.sizePolicy().hasHeightForWidth())
        self.pushButton_add_partner.setSizePolicy(sizePolicy)
        self.pushButton_add_partner.setMinimumSize(QtCore.QSize(345, 44))
        self.pushButton_add_partner.setMaximumSize(QtCore.QSize(190, 44))
        self.pushButton_add_partner.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_add_partner.setObjectName("pushButton_add_partner")
        self.verticalLayout.addWidget(self.pushButton_add_partner)

        self.retranslateUi(Add_partner_def)
        QtCore.QMetaObject.connectSlotsByName(Add_partner_def)

    def retranslateUi(self, Add_partner_def):
        _translate = QtCore.QCoreApplication.translate
        Add_partner_def.setWindowTitle(_translate("Add_partner_def", "Мастер пол | Добавление партнера"))
        self.label.setText(_translate("Add_partner_def", "Тип партнера"))
        self.lineEdit_partnertype.setText(_translate("Add_partner_def", "Тип"))
        self.label_part_name.setText(_translate("Add_partner_def", "Наименование партнера"))
        self.label_director.setText(_translate("Add_partner_def", "Директор"))
        self.label_email.setText(_translate("Add_partner_def", "Электронная почта партнера"))
        self.label_telephone.setText(_translate("Add_partner_def", "Телефон партнера"))
        self.label_ur_addres.setText(_translate("Add_partner_def", "Юридический адрес партнера"))
        self.label_7.setText(_translate("Add_partner_def", "ИНН"))
        self.label_8.setText(_translate("Add_partner_def", "Рейтинг"))
        self.pushButton_add_partner.setText(_translate("Add_partner_def", "Доабвить"))
