# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\Autorization_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Autorization_win(object):
    def setupUi(self, Autorization_win):
        Autorization_win.setObjectName("Autorization_win")
        Autorization_win.resize(550, 550)
        self.verticalLayoutWidget = QtWidgets.QWidget(Autorization_win)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 150, 202, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_role = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_role.setObjectName("comboBox_role")
        self.verticalLayout.addWidget(self.comboBox_role)
        self.lineEdit_login = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login)
        self.lineEdit_password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_autoriz = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_autoriz.setObjectName("pushButton_autoriz")
        self.verticalLayout.addWidget(self.pushButton_autoriz)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        self.commandLinkButton.setAutoExclusive(False)
        self.commandLinkButton.setDefault(False)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout.addWidget(self.commandLinkButton)

        self.retranslateUi(Autorization_win)
        QtCore.QMetaObject.connectSlotsByName(Autorization_win)

    def retranslateUi(self, Autorization_win):
        _translate = QtCore.QCoreApplication.translate
        Autorization_win.setWindowTitle(_translate("Autorization_win", "Авторизация"))
        self.pushButton_autoriz.setText(_translate("Autorization_win", "Войти"))
        self.commandLinkButton.setText(_translate("Autorization_win", "Создать аккаунт"))
