# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\Data_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Data_edit(object):
    def setupUi(self, Data_edit):
        Data_edit.setObjectName("Data_edit")
        Data_edit.resize(344, 412)
        self.gridLayoutWidget = QtWidgets.QWidget(Data_edit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 301, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_user_name_for_de = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_user_name_for_de.setObjectName("comboBox_user_name_for_de")
        self.verticalLayout.addWidget(self.comboBox_user_name_for_de)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox_user_data_change = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_user_data_change.setObjectName("comboBox_user_data_change")
        self.verticalLayout.addWidget(self.comboBox_user_data_change)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_user_data_Edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_user_data_Edit.setObjectName("lineEdit_user_data_Edit")
        self.verticalLayout.addWidget(self.lineEdit_user_data_Edit)
        self.pushButton_save_data_edit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_save_data_edit.setObjectName("pushButton_save_data_edit")
        self.verticalLayout.addWidget(self.pushButton_save_data_edit)

        self.retranslateUi(Data_edit)
        QtCore.QMetaObject.connectSlotsByName(Data_edit)

    def retranslateUi(self, Data_edit):
        _translate = QtCore.QCoreApplication.translate
        Data_edit.setWindowTitle(_translate("Data_edit", "Мастер пол | Изменение данных"))
        self.label.setText(_translate("Data_edit", "Имя партнера"))
        self.label_2.setText(_translate("Data_edit", "Поле длря редактирования"))
        self.label_3.setText(_translate("Data_edit", "Ввод новые данных"))
        self.pushButton_save_data_edit.setText(_translate("Data_edit", "Применить изменения"))
