# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\Manager_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manager_win(object):
    def setupUi(self, Manager_win):
        Manager_win.setObjectName("Manager_win")
        Manager_win.resize(953, 383)
        Manager_win.setMinimumSize(QtCore.QSize(953, 380))
        Manager_win.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.tableView_partners_list = QtWidgets.QTableView(Manager_win)
        self.tableView_partners_list.setGeometry(QtCore.QRect(20, 10, 721, 361))
        self.tableView_partners_list.setObjectName("tableView_partners_list")
        self.layoutWidget = QtWidgets.QWidget(Manager_win)
        self.layoutWidget.setGeometry(QtCore.QRect(750, 10, 191, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_edit_orders = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_edit_orders.setMaximumSize(QtCore.QSize(190, 45))
        self.pushButton_edit_orders.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_edit_orders.setObjectName("pushButton_edit_orders")
        self.verticalLayout.addWidget(self.pushButton_edit_orders)
        self.pushButton_partner_regist = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_partner_regist.setMaximumSize(QtCore.QSize(190, 45))
        self.pushButton_partner_regist.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_partner_regist.setObjectName("pushButton_partner_regist")
        self.verticalLayout.addWidget(self.pushButton_partner_regist)
        self.pushButton_edit_data = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_edit_data.setMaximumSize(QtCore.QSize(190, 45))
        self.pushButton_edit_data.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_edit_data.setObjectName("pushButton_edit_data")
        self.verticalLayout.addWidget(self.pushButton_edit_data)
        self.pushButton_partners_products_realization = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_partners_products_realization.setMaximumSize(QtCore.QSize(190, 45))
        self.pushButton_partners_products_realization.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_partners_products_realization.setObjectName("pushButton_partners_products_realization")
        self.verticalLayout.addWidget(self.pushButton_partners_products_realization)
        self.pushButton_calculate_m = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_calculate_m.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_calculate_m.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_calculate_m.setObjectName("pushButton_calculate_m")
        self.verticalLayout.addWidget(self.pushButton_calculate_m)
        self.pushButton_exit_m = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_exit_m.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_exit_m.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_exit_m.setObjectName("pushButton_exit_m")
        self.verticalLayout.addWidget(self.pushButton_exit_m)

        self.retranslateUi(Manager_win)
        QtCore.QMetaObject.connectSlotsByName(Manager_win)

    def retranslateUi(self, Manager_win):
        _translate = QtCore.QCoreApplication.translate
        Manager_win.setWindowTitle(_translate("Manager_win", "Мастер пол | Управление"))
        self.pushButton_edit_orders.setText(_translate("Manager_win", "Заказы"))
        self.pushButton_partner_regist.setText(_translate("Manager_win", "Регистрация партнера"))
        self.pushButton_edit_data.setText(_translate("Manager_win", "Изменить данные"))
        self.pushButton_partners_products_realization.setText(_translate("Manager_win", "Таблица реализации продукции"))
        self.pushButton_calculate_m.setText(_translate("Manager_win", "Рассчет продукции"))
        self.pushButton_exit_m.setText(_translate("Manager_win", "Выход"))
