# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\order_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_order_history(object):
    def setupUi(self, Dialog_order_history):
        Dialog_order_history.setObjectName("Dialog_order_history")
        Dialog_order_history.resize(696, 489)
        Dialog_order_history.setMinimumSize(QtCore.QSize(696, 489))
        Dialog_order_history.setMaximumSize(QtCore.QSize(696, 489))
        Dialog_order_history.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.layoutWidget = QtWidgets.QWidget(Dialog_order_history)
        self.layoutWidget.setGeometry(QtCore.QRect(430, 10, 250, 137))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_name_change = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_name_change.setMinimumSize(QtCore.QSize(121, 0))
        self.comboBox_name_change.setObjectName("comboBox_name_change")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_name_change)
        self.pushButton_cancel_order = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(121)
        sizePolicy.setVerticalStretch(121)
        sizePolicy.setHeightForWidth(self.pushButton_cancel_order.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel_order.setSizePolicy(sizePolicy)
        self.pushButton_cancel_order.setMinimumSize(QtCore.QSize(121, 55))
        self.pushButton_cancel_order.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_cancel_order.setObjectName("pushButton_cancel_order")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_cancel_order)
        self.pushButton_buy = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(121)
        sizePolicy.setVerticalStretch(121)
        sizePolicy.setHeightForWidth(self.pushButton_buy.sizePolicy().hasHeightForWidth())
        self.pushButton_buy.setSizePolicy(sizePolicy)
        self.pushButton_buy.setMinimumSize(QtCore.QSize(121, 55))
        self.pushButton_buy.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_buy.setObjectName("pushButton_buy")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_buy)
        self.comboBox_change_order = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_change_order.setMinimumSize(QtCore.QSize(121, 0))
        self.comboBox_change_order.setObjectName("comboBox_change_order")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.comboBox_change_order)
        self.tableWidget_orders_output = QtWidgets.QTableWidget(Dialog_order_history)
        self.tableWidget_orders_output.setGeometry(QtCore.QRect(0, 0, 421, 491))
        self.tableWidget_orders_output.setObjectName("tableWidget_orders_output")
        self.tableWidget_orders_output.setColumnCount(0)
        self.tableWidget_orders_output.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(Dialog_order_history)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(430, 150, 111, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(55)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(111, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\QtDesign\\../task and images/Мастер пол.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog_order_history)
        QtCore.QMetaObject.connectSlotsByName(Dialog_order_history)

    def retranslateUi(self, Dialog_order_history):
        _translate = QtCore.QCoreApplication.translate
        Dialog_order_history.setWindowTitle(_translate("Dialog_order_history", "Мастер пол | Просмотр заказов"))
        self.label.setText(_translate("Dialog_order_history", "Выберите заказ"))
        self.pushButton_cancel_order.setText(_translate("Dialog_order_history", "Отменить заказ"))
        self.pushButton_buy.setText(_translate("Dialog_order_history", "Оплатить"))
