# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\Orders_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialo_edit_orders(object):
    def setupUi(self, Dialo_edit_orders):
        Dialo_edit_orders.setObjectName("Dialo_edit_orders")
        Dialo_edit_orders.resize(874, 563)
        Dialo_edit_orders.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.tableWidget_orders_output = QtWidgets.QTableWidget(Dialo_edit_orders)
        self.tableWidget_orders_output.setGeometry(QtCore.QRect(10, 10, 571, 331))
        self.tableWidget_orders_output.setObjectName("tableWidget_orders_output")
        self.tableWidget_orders_output.setColumnCount(0)
        self.tableWidget_orders_output.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(Dialo_edit_orders)
        self.layoutWidget.setGeometry(QtCore.QRect(600, 20, 251, 259))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_change_name_partner = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_change_name_partner.setMinimumSize(QtCore.QSize(121, 0))
        self.comboBox_change_name_partner.setObjectName("comboBox_change_name_partner")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_change_name_partner)
        self.pushButton_confirm_order = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(121)
        sizePolicy.setVerticalStretch(121)
        sizePolicy.setHeightForWidth(self.pushButton_confirm_order.sizePolicy().hasHeightForWidth())
        self.pushButton_confirm_order.setSizePolicy(sizePolicy)
        self.pushButton_confirm_order.setMinimumSize(QtCore.QSize(121, 55))
        self.pushButton_confirm_order.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_confirm_order.setObjectName("pushButton_confirm_order")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_confirm_order)
        self.pushButton_canceled_order = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(121)
        sizePolicy.setVerticalStretch(121)
        sizePolicy.setHeightForWidth(self.pushButton_canceled_order.sizePolicy().hasHeightForWidth())
        self.pushButton_canceled_order.setSizePolicy(sizePolicy)
        self.pushButton_canceled_order.setMinimumSize(QtCore.QSize(121, 55))
        self.pushButton_canceled_order.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_canceled_order.setObjectName("pushButton_canceled_order")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_canceled_order)
        self.comboBox_change_order_partner = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_change_order_partner.setMinimumSize(QtCore.QSize(121, 0))
        self.comboBox_change_order_partner.setObjectName("comboBox_change_order_partner")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.comboBox_change_order_partner)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.pushButton_in_process = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(121)
        sizePolicy.setVerticalStretch(121)
        sizePolicy.setHeightForWidth(self.pushButton_in_process.sizePolicy().hasHeightForWidth())
        self.pushButton_in_process.setSizePolicy(sizePolicy)
        self.pushButton_in_process.setMinimumSize(QtCore.QSize(121, 55))
        self.pushButton_in_process.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_in_process.setObjectName("pushButton_in_process")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_in_process)
        self.pushButton_order_created = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(121)
        sizePolicy.setVerticalStretch(121)
        sizePolicy.setHeightForWidth(self.pushButton_order_created.sizePolicy().hasHeightForWidth())
        self.pushButton_order_created.setSizePolicy(sizePolicy)
        self.pushButton_order_created.setMinimumSize(QtCore.QSize(121, 55))
        self.pushButton_order_created.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_order_created.setObjectName("pushButton_order_created")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_order_created)

        self.retranslateUi(Dialo_edit_orders)
        QtCore.QMetaObject.connectSlotsByName(Dialo_edit_orders)

    def retranslateUi(self, Dialo_edit_orders):
        _translate = QtCore.QCoreApplication.translate
        Dialo_edit_orders.setWindowTitle(_translate("Dialo_edit_orders", "Мастер пол | Просмотр заказов"))
        self.label.setText(_translate("Dialo_edit_orders", "Выберите заказ"))
        self.pushButton_confirm_order.setText(_translate("Dialo_edit_orders", "Принять заказ"))
        self.pushButton_canceled_order.setText(_translate("Dialo_edit_orders", "Отклонить заказ"))
        self.label_2.setText(_translate("Dialo_edit_orders", "Изменить статус заказа"))
        self.pushButton_in_process.setText(_translate("Dialo_edit_orders", "В процессе"))
        self.pushButton_order_created.setText(_translate("Dialo_edit_orders", "Создан"))
