# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\Products_type_method.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_products_method(object):
    def setupUi(self, Dialog_products_method):
        Dialog_products_method.setObjectName("Dialog_products_method")
        Dialog_products_method.resize(486, 381)
        Dialog_products_method.setMinimumSize(QtCore.QSize(486, 381))
        Dialog_products_method.setMaximumSize(QtCore.QSize(486, 381))
        Dialog_products_method.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_products_method)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 60, 160, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_products_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_products_type.setObjectName("comboBox_products_type")
        self.verticalLayout.addWidget(self.comboBox_products_type)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.comboBox_material_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_material_type.setObjectName("comboBox_material_type")
        self.verticalLayout.addWidget(self.comboBox_material_type)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_products = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_products.setObjectName("lineEdit_products")
        self.verticalLayout.addWidget(self.lineEdit_products)
        self.pushButton_calculation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(111)
        sizePolicy.setHeightForWidth(self.pushButton_calculation.sizePolicy().hasHeightForWidth())
        self.pushButton_calculation.setSizePolicy(sizePolicy)
        self.pushButton_calculation.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_calculation.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_calculation.setObjectName("pushButton_calculation")
        self.verticalLayout.addWidget(self.pushButton_calculation)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog_products_method)
        self.formLayoutWidget.setGeometry(QtCore.QRect(270, 60, 235, 87))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_the_marriage_percentage = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_the_marriage_percentage.setObjectName("label_the_marriage_percentage")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_the_marriage_percentage)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)

        self.retranslateUi(Dialog_products_method)
        QtCore.QMetaObject.connectSlotsByName(Dialog_products_method)

    def retranslateUi(self, Dialog_products_method):
        _translate = QtCore.QCoreApplication.translate
        Dialog_products_method.setWindowTitle(_translate("Dialog_products_method", "Dialog"))
        self.label.setText(_translate("Dialog_products_method", "Тип продукции"))
        self.label_6.setText(_translate("Dialog_products_method", "Тип материала"))
        self.label_5.setText(_translate("Dialog_products_method", "Количество продукции"))
        self.pushButton_calculation.setText(_translate("Dialog_products_method", "Рассчитать "))
        self.label_2.setText(_translate("Dialog_products_method", "Процент барка:"))
        self.label_4.setText(_translate("Dialog_products_method", "Количество необходимого материала:"))
        self.label_the_marriage_percentage.setText(_translate("Dialog_products_method", "%"))
        self.label_7.setText(_translate("Dialog_products_method", "?"))
