# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\products_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_products_table(object):
    def setupUi(self, Dialog_products_table):
        Dialog_products_table.setObjectName("Dialog_products_table")
        Dialog_products_table.resize(688, 488)
        Dialog_products_table.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog_products_table)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 641, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_products_output = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget_products_output.setObjectName("tableWidget_products_output")
        self.tableWidget_products_output.setColumnCount(0)
        self.tableWidget_products_output.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_products_output, 0, 0, 1, 1)

        self.retranslateUi(Dialog_products_table)
        QtCore.QMetaObject.connectSlotsByName(Dialog_products_table)

    def retranslateUi(self, Dialog_products_table):
        _translate = QtCore.QCoreApplication.translate
        Dialog_products_table.setWindowTitle(_translate("Dialog_products_table", "Dialog"))
