# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\realisation_partner_products.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_realistaio_products_table(object):
    def setupUi(self, Dialog_realistaio_products_table):
        Dialog_realistaio_products_table.setObjectName("Dialog_realistaio_products_table")
        Dialog_realistaio_products_table.resize(831, 541)
        Dialog_realistaio_products_table.setMaximumSize(QtCore.QSize(831, 541))
        Dialog_realistaio_products_table.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.tableView_realisation_product_view = QtWidgets.QTableView(Dialog_realistaio_products_table)
        self.tableView_realisation_product_view.setGeometry(QtCore.QRect(0, 0, 841, 541))
        self.tableView_realisation_product_view.setObjectName("tableView_realisation_product_view")

        self.retranslateUi(Dialog_realistaio_products_table)
        QtCore.QMetaObject.connectSlotsByName(Dialog_realistaio_products_table)

    def retranslateUi(self, Dialog_realistaio_products_table):
        _translate = QtCore.QCoreApplication.translate
        Dialog_realistaio_products_table.setWindowTitle(_translate("Dialog_realistaio_products_table", "Мастиер пол | История реализации продукции"))
