# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\Registration_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration_win(object):
    def setupUi(self, Registration_win):
        Registration_win.setObjectName("Registration_win")
        Registration_win.resize(550, 550)
        self.verticalLayoutWidget = QtWidgets.QWidget(Registration_win)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 150, 202, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_registr = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_registr.setObjectName("comboBox_registr")
        self.verticalLayout.addWidget(self.comboBox_registr)
        self.lineEdit_login_registr = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_login_registr.setObjectName("lineEdit_login_registr")
        self.verticalLayout.addWidget(self.lineEdit_login_registr)
        self.lineEdit_password_regist = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_password_regist.setObjectName("lineEdit_password_regist")
        self.verticalLayout.addWidget(self.lineEdit_password_regist)
        self.lineEdit_repit_pass_auto = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_repit_pass_auto.setObjectName("lineEdit_repit_pass_auto")
        self.verticalLayout.addWidget(self.lineEdit_repit_pass_auto)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_registration = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_registration.setObjectName("pushButton_registration")
        self.verticalLayout.addWidget(self.pushButton_registration)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        self.commandLinkButton.setAutoExclusive(False)
        self.commandLinkButton.setDefault(False)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout.addWidget(self.commandLinkButton)

        self.retranslateUi(Registration_win)
        QtCore.QMetaObject.connectSlotsByName(Registration_win)

    def retranslateUi(self, Registration_win):
        _translate = QtCore.QCoreApplication.translate
        Registration_win.setWindowTitle(_translate("Registration_win", "Регистрация"))
        self.pushButton_registration.setText(_translate("Registration_win", "Войти"))
        self.commandLinkButton.setText(_translate("Registration_win", "Авторизироваться"))
